package main

import "github.com/go-pg/migrations/v8"

func init() {
	migrations.MustRegisterTx(func(db migrations.DB) error {
		return execSome(db, `
			CREATE TABLE storjnet.client_errors (
				id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				url text NOT NULL,
				user_id int,
				user_agent text,
				lang text,
				message text NOT NULL,
				stack text,
				created_at timestamptz NOT NULL DEFAULT now()
			)
			`)
	}, func(db migrations.DB) error {
		return execSome(db, `
			DROP TABLE storjnet.client_errors
			`)
	})
}
