package utils

var Countries = []*Country{
	{A2: `af`, A3: `afg`, EN: `Afghanistan`, RU: `Афганистан`},
	{A2: `ax`, A3: `ala`, EN: `Åland Islands`, RU: `Аландские острова`},
	{A2: `al`, A3: `alb`, EN: `Albania`, RU: `Албания`},
	{A2: `dz`, A3: `dza`, EN: `Algeria`, RU: `Алжир`},
	{A2: `as`, A3: `asm`, EN: `American Samoa`, RU: `Американское Самоа`},
	{A2: `ad`, A3: `and`, EN: `Andorra`, RU: `Андорра`},
	{A2: `ao`, A3: `ago`, EN: `Angola`, RU: `Ангола`},
	{A2: `ai`, A3: `aia`, EN: `Anguilla`, RU: `Ангилья`},
	{A2: `aq`, A3: `ata`, EN: `Antarctica`, RU: `Антарктика`},
	{A2: `ag`, A3: `atg`, EN: `Antigua and Barbuda`, RU: `Антигуа и Барбуда`},
	{A2: `ar`, A3: `arg`, EN: `Argentina`, RU: `Аргентина`},
	{A2: `am`, A3: `arm`, EN: `Armenia`, RU: `Армения`},
	{A2: `aw`, A3: `abw`, EN: `Aruba`, RU: `Аруба`},
	{A2: `au`, A3: `aus`, EN: `Australia`, RU: `Австралия`},
	{A2: `at`, A3: `aut`, EN: `Austria`, RU: `Австрия`},
	{A2: `az`, A3: `aze`, EN: `Azerbaijan`, RU: `Азербайджан`},
	{A2: `bs`, A3: `bhs`, EN: `Bahamas`, RU: `Багамские Острова`},
	{A2: `bh`, A3: `bhr`, EN: `Bahrain`, RU: `Бахрейн`},
	{A2: `bd`, A3: `bgd`, EN: `Bangladesh`, RU: `Бангладеш`},
	{A2: `bb`, A3: `brb`, EN: `Barbados`, RU: `Барбадос`},
	{A2: `by`, A3: `blr`, EN: `Belarus`, RU: `Беларусь`},
	{A2: `be`, A3: `bel`, EN: `Belgium`, RU: `Бельгия`},
	{A2: `bz`, A3: `blz`, EN: `Belize`, RU: `Белиз`},
	{A2: `bj`, A3: `ben`, EN: `Benin`, RU: `Бенин`},
	{A2: `bm`, A3: `bmu`, EN: `Bermuda`, RU: `Бермуды`},
	{A2: `bt`, A3: `btn`, EN: `Bhutan`, RU: `Бутан`},
	{A2: `bo`, A3: `bol`, EN: `Bolivia`, RU: `Боливия`},
	{A2: `bq`, A3: `bes`, EN: `Bonaire, Sint Eustatius and Saba`, RU: `Бонайре, Синт-Эстатиус и Саба`},
	{A2: `ba`, A3: `bih`, EN: `Bosnia and Herzegovina`, RU: `Босния и Герцеговина`},
	{A2: `bw`, A3: `bwa`, EN: `Botswana`, RU: `Ботсвана`},
	{A2: `bv`, A3: `bvt`, EN: `Bouvet Island`, RU: `Остров Буве`},
	{A2: `br`, A3: `bra`, EN: `Brazil`, RU: `Бразилия`},
	{A2: `io`, A3: `iot`, EN: `British Indian Ocean Territory`, RU: `Британская Территория в Индийском Океане`},
	{A2: `bn`, A3: `brn`, EN: `Brunei Darussalam`, RU: `Бруней`},
	{A2: `bg`, A3: `bgr`, EN: `Bulgaria`, RU: `Болгария`},
	{A2: `bf`, A3: `bfa`, EN: `Burkina Faso`, RU: `Буркина-Фасо`},
	{A2: `bi`, A3: `bdi`, EN: `Burundi`, RU: `Бурунди`},
	{A2: `kh`, A3: `khm`, EN: `Cambodia`, RU: `Камбоджа`},
	{A2: `cm`, A3: `cmr`, EN: `Cameroon`, RU: `Камерун`},
	{A2: `ca`, A3: `can`, EN: `Canada`, RU: `Канада`},
	{A2: `cv`, A3: `cpv`, EN: `Cabo Verde`, RU: `Кабо-Верде`},
	{A2: `ky`, A3: `cym`, EN: `Cayman Islands`, RU: `Острова Кайман`},
	{A2: `cf`, A3: `caf`, EN: `Central African Republic`, RU: `ЦАР`},
	{A2: `td`, A3: `tcd`, EN: `Chad`, RU: `Чад`},
	{A2: `cl`, A3: `chl`, EN: `Chile`, RU: `Чили`},
	{A2: `cn`, A3: `chn`, EN: `China`, RU: `Китай`},
	{A2: `cx`, A3: `cxr`, EN: `Christmas Island`, RU: `Остров Рождества`},
	{A2: `cc`, A3: `cck`, EN: `Cocos (Keeling) Islands`, RU: `Кокосовые острова`},
	{A2: `co`, A3: `col`, EN: `Colombia`, RU: `Колумбия`},
	{A2: `km`, A3: `com`, EN: `Comoros`, RU: `Коморы`},
	{A2: `cg`, A3: `cog`, EN: `Congo`, RU: `Республика Конго`},
	{A2: `cd`, A3: `cod`, EN: `Congo, Democratic Republic of the`, RU: `ДР Конго`},
	{A2: `ck`, A3: `cok`, EN: `Cook Islands`, RU: `Острова Кука`},
	{A2: `cr`, A3: `cri`, EN: `Costa Rica`, RU: `Коста-Рика`},
	{A2: `ci`, A3: `civ`, EN: `Côte d'Ivoire`, RU: `Кот-д’Ивуар`},
	{A2: `hr`, A3: `hrv`, EN: `Croatia`, RU: `Хорватия`},
	{A2: `cu`, A3: `cub`, EN: `Cuba`, RU: `Куба`},
	{A2: `cw`, A3: `cuw`, EN: `Curaçao`, RU: `Кюрасао`},
	{A2: `cy`, A3: `cyp`, EN: `Cyprus`, RU: `Кипр`},
	{A2: `cz`, A3: `cze`, EN: `Czechia`, RU: `Чехия`},
	{A2: `dk`, A3: `dnk`, EN: `Denmark`, RU: `Дания`},
	{A2: `dj`, A3: `dji`, EN: `Djibouti`, RU: `Джибути`},
	{A2: `dm`, A3: `dma`, EN: `Dominica`, RU: `Доминика`},
	{A2: `do`, A3: `dom`, EN: `Dominican Republic`, RU: `Доминиканская Республика`},
	{A2: `ec`, A3: `ecu`, EN: `Ecuador`, RU: `Эквадор`},
	{A2: `eg`, A3: `egy`, EN: `Egypt`, RU: `Египет`},
	{A2: `sv`, A3: `slv`, EN: `El Salvador`, RU: `Сальвадор`},
	{A2: `gq`, A3: `gnq`, EN: `Equatorial Guinea`, RU: `Экваториальная Гвинея`},
	{A2: `er`, A3: `eri`, EN: `Eritrea`, RU: `Эритрея`},
	{A2: `ee`, A3: `est`, EN: `Estonia`, RU: `Эстония`},
	{A2: `et`, A3: `eth`, EN: `Ethiopia`, RU: `Эфиопия`},
	{A2: `fk`, A3: `flk`, EN: `Falkland Islands (Malvinas)`, RU: `Фолклендские острова`},
	{A2: `fo`, A3: `fro`, EN: `Faroe Islands`, RU: `Фарерские острова`},
	{A2: `fj`, A3: `fji`, EN: `Fiji`, RU: `Фиджи`},
	{A2: `fi`, A3: `fin`, EN: `Finland`, RU: `Финляндия`},
	{A2: `fr`, A3: `fra`, EN: `France`, RU: `Франция`},
	{A2: `gf`, A3: `guf`, EN: `French Guiana`, RU: `Гвиана`},
	{A2: `pf`, A3: `pyf`, EN: `French Polynesia`, RU: `Французская Полинезия`},
	{A2: `tf`, A3: `atf`, EN: `French Southern Territories`, RU: `Французские Южные и Антарктические территории`},
	{A2: `ga`, A3: `gab`, EN: `Gabon`, RU: `Габон`},
	{A2: `gm`, A3: `gmb`, EN: `Gambia`, RU: `Гамбия`},
	{A2: `ge`, A3: `geo`, EN: `Georgia`, RU: `Грузия`},
	{A2: `de`, A3: `deu`, EN: `Germany`, RU: `Германия`},
	{A2: `gh`, A3: `gha`, EN: `Ghana`, RU: `Гана`},
	{A2: `gi`, A3: `gib`, EN: `Gibraltar`, RU: `Гибралтар`},
	{A2: `gr`, A3: `grc`, EN: `Greece`, RU: `Греция`},
	{A2: `gl`, A3: `grl`, EN: `Greenland`, RU: `Гренландия`},
	{A2: `gd`, A3: `grd`, EN: `Grenada`, RU: `Гренада`},
	{A2: `gp`, A3: `glp`, EN: `Guadeloupe`, RU: `Гваделупа`},
	{A2: `gu`, A3: `gum`, EN: `Guam`, RU: `Гуам`},
	{A2: `gt`, A3: `gtm`, EN: `Guatemala`, RU: `Гватемала`},
	{A2: `gg`, A3: `ggy`, EN: `Guernsey`, RU: `Гернси`},
	{A2: `gn`, A3: `gin`, EN: `Guinea`, RU: `Гвинея`},
	{A2: `gw`, A3: `gnb`, EN: `Guinea-Bissau`, RU: `Гвинея-Бисау`},
	{A2: `gy`, A3: `guy`, EN: `Guyana`, RU: `Гайана`},
	{A2: `ht`, A3: `hti`, EN: `Haiti`, RU: `Гаити`},
	{A2: `hm`, A3: `hmd`, EN: `Heard Island and McDonald Islands`, RU: `Херд и Макдональд`},
	{A2: `va`, A3: `vat`, EN: `Holy See`, RU: `Ватикан`},
	{A2: `hn`, A3: `hnd`, EN: `Honduras`, RU: `Гондурас`},
	{A2: `hk`, A3: `hkg`, EN: `Hong Kong`, RU: `Гонконг`},
	{A2: `hu`, A3: `hun`, EN: `Hungary`, RU: `Венгрия`},
	{A2: `is`, A3: `isl`, EN: `Iceland`, RU: `Исландия`},
	{A2: `in`, A3: `ind`, EN: `India`, RU: `Индия`},
	{A2: `id`, A3: `idn`, EN: `Indonesia`, RU: `Индонезия`},
	{A2: `ir`, A3: `irn`, EN: `Iran`, RU: `Иран`},
	{A2: `iq`, A3: `irq`, EN: `Iraq`, RU: `Ирак`},
	{A2: `ie`, A3: `irl`, EN: `Ireland`, RU: `Ирландия`},
	{A2: `im`, A3: `imn`, EN: `Isle of Man`, RU: `Остров Мэн`},
	{A2: `il`, A3: `isr`, EN: `Israel`, RU: `Израиль`},
	{A2: `it`, A3: `ita`, EN: `Italy`, RU: `Италия`},
	{A2: `jm`, A3: `jam`, EN: `Jamaica`, RU: `Ямайка`},
	{A2: `jp`, A3: `jpn`, EN: `Japan`, RU: `Япония`},
	{A2: `je`, A3: `jey`, EN: `Jersey`, RU: `Джерси`},
	{A2: `jo`, A3: `jor`, EN: `Jordan`, RU: `Иордания`},
	{A2: `kz`, A3: `kaz`, EN: `Kazakhstan`, RU: `Казахстан`},
	{A2: `ke`, A3: `ken`, EN: `Kenya`, RU: `Кения`},
	{A2: `ki`, A3: `kir`, EN: `Kiribati`, RU: `Кирибати`},
	{A2: `kp`, A3: `prk`, EN: `North Korea`, RU: `Северная Корея`},
	{A2: `kr`, A3: `kor`, EN: `South Korea`, RU: `Южная Корея`},
	{A2: `kw`, A3: `kwt`, EN: `Kuwait`, RU: `Кувейт`},
	{A2: `kg`, A3: `kgz`, EN: `Kyrgyzstan`, RU: `Кыргызстан`},
	{A2: `la`, A3: `lao`, EN: `Lao People's Democratic Republic`, RU: `Лаос`},
	{A2: `lv`, A3: `lva`, EN: `Latvia`, RU: `Латвия`},
	{A2: `lb`, A3: `lbn`, EN: `Lebanon`, RU: `Ливан`},
	{A2: `ls`, A3: `lso`, EN: `Lesotho`, RU: `Лесото`},
	{A2: `lr`, A3: `lbr`, EN: `Liberia`, RU: `Либерия`},
	{A2: `ly`, A3: `lby`, EN: `Libya`, RU: `Ливия`},
	{A2: `li`, A3: `lie`, EN: `Liechtenstein`, RU: `Лихтенштейн`},
	{A2: `lt`, A3: `ltu`, EN: `Lithuania`, RU: `Литва`},
	{A2: `lu`, A3: `lux`, EN: `Luxembourg`, RU: `Люксембург`},
	{A2: `mo`, A3: `mac`, EN: `Macao`, RU: `Макао`},
	{A2: `mk`, A3: `mkd`, EN: `North Macedonia`, RU: `Северная Македония`},
	{A2: `mg`, A3: `mdg`, EN: `Madagascar`, RU: `Мадагаскар`},
	{A2: `mw`, A3: `mwi`, EN: `Malawi`, RU: `Малави`},
	{A2: `my`, A3: `mys`, EN: `Malaysia`, RU: `Малайзия`},
	{A2: `mv`, A3: `mdv`, EN: `Maldives`, RU: `Мальдивы`},
	{A2: `ml`, A3: `mli`, EN: `Mali`, RU: `Мали`},
	{A2: `mt`, A3: `mlt`, EN: `Malta`, RU: `Мальта`},
	{A2: `mh`, A3: `mhl`, EN: `Marshall Islands`, RU: `Маршалловы Острова`},
	{A2: `mq`, A3: `mtq`, EN: `Martinique`, RU: `Мартиника`},
	{A2: `mr`, A3: `mrt`, EN: `Mauritania`, RU: `Мавритания`},
	{A2: `mu`, A3: `mus`, EN: `Mauritius`, RU: `Маврикий`},
	{A2: `yt`, A3: `myt`, EN: `Mayotte`, RU: `Майотта`},
	{A2: `mx`, A3: `mex`, EN: `Mexico`, RU: `Мексика`},
	{A2: `fm`, A3: `fsm`, EN: `Micronesia`, RU: `Микронезия`},
	{A2: `ma`, A3: `mar`, EN: `Morocco`, RU: `Марокко`},
	{A2: `md`, A3: `mda`, EN: `Moldova`, RU: `Молдова`},
	{A2: `mc`, A3: `mco`, EN: `Monaco`, RU: `Монако`},
	{A2: `mn`, A3: `mng`, EN: `Mongolia`, RU: `Монголия`},
	{A2: `me`, A3: `mne`, EN: `Montenegro`, RU: `Черногория`},
	{A2: `ms`, A3: `msr`, EN: `Montserrat`, RU: `Монтсеррат`},
	{A2: `mz`, A3: `moz`, EN: `Mozambique`, RU: `Мозамбик`},
	{A2: `mm`, A3: `mmr`, EN: `Myanmar`, RU: `Мьянма`},
	{A2: `na`, A3: `nam`, EN: `Namibia`, RU: `Намибия`},
	{A2: `nr`, A3: `nru`, EN: `Nauru`, RU: `Науру`},
	{A2: `np`, A3: `npl`, EN: `Nepal`, RU: `Непал`},
	{A2: `nl`, A3: `nld`, EN: `Netherlands`, RU: `Нидерланды`},
	{A2: `nc`, A3: `ncl`, EN: `New Caledonia`, RU: `Новая Каледония`},
	{A2: `nz`, A3: `nzl`, EN: `New Zealand`, RU: `Новая Зеландия`},
	{A2: `ni`, A3: `nic`, EN: `Nicaragua`, RU: `Никарагуа`},
	{A2: `ne`, A3: `ner`, EN: `Niger`, RU: `Нигер`},
	{A2: `ng`, A3: `nga`, EN: `Nigeria`, RU: `Нигерия`},
	{A2: `nu`, A3: `niu`, EN: `Niue`, RU: `Ниуэ`},
	{A2: `nf`, A3: `nfk`, EN: `Norfolk Island`, RU: `Остров Норфолк`},
	{A2: `mp`, A3: `mnp`, EN: `Northern Mariana Islands`, RU: `Северные Марианские Острова`},
	{A2: `no`, A3: `nor`, EN: `Norway`, RU: `Норвегия`},
	{A2: `om`, A3: `omn`, EN: `Oman`, RU: `Оман`},
	{A2: `pk`, A3: `pak`, EN: `Pakistan`, RU: `Пакистан`},
	{A2: `pw`, A3: `plw`, EN: `Palau`, RU: `Палау`},
	{A2: `ps`, A3: `pse`, EN: `Palestine`, RU: `Государство Палестина`},
	{A2: `pa`, A3: `pan`, EN: `Panama`, RU: `Панама`},
	{A2: `pg`, A3: `png`, EN: `Papua New Guinea`, RU: `Папуа — Новая Гвинея`},
	{A2: `py`, A3: `pry`, EN: `Paraguay`, RU: `Парагвай`},
	{A2: `pe`, A3: `per`, EN: `Peru`, RU: `Перу`},
	{A2: `ph`, A3: `phl`, EN: `Philippines`, RU: `Филиппины`},
	{A2: `pn`, A3: `pcn`, EN: `Pitcairn`, RU: `Острова Питкэрн`},
	{A2: `pl`, A3: `pol`, EN: `Poland`, RU: `Польша`},
	{A2: `pt`, A3: `prt`, EN: `Portugal`, RU: `Португалия`},
	{A2: `pr`, A3: `pri`, EN: `Puerto Rico`, RU: `Пуэрто-Рико`},
	{A2: `qa`, A3: `qat`, EN: `Qatar`, RU: `Катар`},
	{A2: `re`, A3: `reu`, EN: `Réunion`, RU: `Реюньон`},
	{A2: `ro`, A3: `rou`, EN: `Romania`, RU: `Румыния`},
	{A2: `ru`, A3: `rus`, EN: `Russia`, RU: `Россия`},
	{A2: `rw`, A3: `rwa`, EN: `Rwanda`, RU: `Руанда`},
	{A2: `bl`, A3: `blm`, EN: `Saint Barthélemy`, RU: `Сен-Бартелеми`},
	{A2: `sh`, A3: `shn`, EN: `Saint Helena, Ascension and Tristan da Cunha`, RU: `Остров Святой Елены`},
	{A2: `kn`, A3: `kna`, EN: `Saint Kitts and Nevis`, RU: `Сент-Китс и Невис`},
	{A2: `lc`, A3: `lca`, EN: `Saint Lucia`, RU: `Сент-Люсия`},
	{A2: `mf`, A3: `maf`, EN: `Saint Martin (French part)`, RU: `Сен-Мартен`},
	{A2: `pm`, A3: `spm`, EN: `Saint Pierre and Miquelon`, RU: `Сен-Пьер и Микелон`},
	{A2: `vc`, A3: `vct`, EN: `Saint Vincent and the Grenadines`, RU: `Сент-Винсент и Гренадины`},
	{A2: `ws`, A3: `wsm`, EN: `Samoa`, RU: `Самоа`},
	{A2: `sm`, A3: `smr`, EN: `San Marino`, RU: `Сан-Марино`},
	{A2: `st`, A3: `stp`, EN: `Sao Tome and Principe`, RU: `Сан-Томе и Принсипи`},
	{A2: `sa`, A3: `sau`, EN: `Saudi Arabia`, RU: `Саудовская Аравия`},
	{A2: `sn`, A3: `sen`, EN: `Senegal`, RU: `Сенегал`},
	{A2: `rs`, A3: `srb`, EN: `Serbia`, RU: `Сербия`},
	{A2: `sc`, A3: `syc`, EN: `Seychelles`, RU: `Сейшельские Острова`},
	{A2: `sl`, A3: `sle`, EN: `Sierra Leone`, RU: `Сьерра-Леоне`},
	{A2: `sg`, A3: `sgp`, EN: `Singapore`, RU: `Сингапур`},
	{A2: `sx`, A3: `sxm`, EN: `Sint Maarten (Dutch part)`, RU: `Синт-Мартен`},
	{A2: `sk`, A3: `svk`, EN: `Slovakia`, RU: `Словакия`},
	{A2: `si`, A3: `svn`, EN: `Slovenia`, RU: `Словения`},
	{A2: `sb`, A3: `slb`, EN: `Solomon Islands`, RU: `Соломоновы Острова`},
	{A2: `so`, A3: `som`, EN: `Somalia`, RU: `Сомали`},
	{A2: `za`, A3: `zaf`, EN: `South Africa`, RU: `ЮАР`},
	{A2: `gs`, A3: `sgs`, EN: `South Georgia and the South Sandwich Islands`, RU: `Южная Георгия и Южные Сандвичевы Острова`},
	{A2: `ss`, A3: `ssd`, EN: `South Sudan`, RU: `Южный Судан`},
	{A2: `es`, A3: `esp`, EN: `Spain`, RU: `Испания`},
	{A2: `lk`, A3: `lka`, EN: `Sri Lanka`, RU: `Шри-Ланка`},
	{A2: `sd`, A3: `sdn`, EN: `Sudan`, RU: `Судан`},
	{A2: `sr`, A3: `sur`, EN: `Suriname`, RU: `Суринам`},
	{A2: `sj`, A3: `sjm`, EN: `Svalbard and Jan Mayen`, RU: `Шпицберген и Ян-Майен`},
	{A2: `sz`, A3: `swz`, EN: `Eswatini`, RU: `Эсватини`},
	{A2: `se`, A3: `swe`, EN: `Sweden`, RU: `Швеция`},
	{A2: `ch`, A3: `che`, EN: `Switzerland`, RU: `Швейцария`},
	{A2: `sy`, A3: `syr`, EN: `Syrian Arab Republic`, RU: `Сирия`},
	{A2: `tw`, A3: `twn`, EN: `Taiwan`, RU: `Тайвань`},
	{A2: `tj`, A3: `tjk`, EN: `Tajikistan`, RU: `Таджикистан`},
	{A2: `tz`, A3: `tza`, EN: `Tanzania`, RU: `Танзания`},
	{A2: `th`, A3: `tha`, EN: `Thailand`, RU: `Таиланд`},
	{A2: `tl`, A3: `tls`, EN: `Timor-Leste`, RU: `Восточный Тимор`},
	{A2: `tg`, A3: `tgo`, EN: `Togo`, RU: `Того`},
	{A2: `tk`, A3: `tkl`, EN: `Tokelau`, RU: `Токелау`},
	{A2: `to`, A3: `ton`, EN: `Tonga`, RU: `Тонга`},
	{A2: `tt`, A3: `tto`, EN: `Trinidad and Tobago`, RU: `Тринидад и Тобаго`},
	{A2: `tn`, A3: `tun`, EN: `Tunisia`, RU: `Тунис`},
	{A2: `tr`, A3: `tur`, EN: `Türkiye`, RU: `Турция`},
	{A2: `tm`, A3: `tkm`, EN: `Turkmenistan`, RU: `Туркменистан`},
	{A2: `tc`, A3: `tca`, EN: `Turks and Caicos Islands`, RU: `Теркс и Кайкос`},
	{A2: `tv`, A3: `tuv`, EN: `Tuvalu`, RU: `Тувалу`},
	{A2: `ug`, A3: `uga`, EN: `Uganda`, RU: `Уганда`},
	{A2: `ua`, A3: `ukr`, EN: `Ukraine`, RU: `Украина`},
	{A2: `ae`, A3: `are`, EN: `United Arab Emirates`, RU: `ОАЭ`},
	{A2: `gb`, A3: `gbr`, EN: `United Kingdom`, RU: `Великобритания`},
	{A2: `us`, A3: `usa`, EN: `United States`, RU: `США`},
	{A2: `um`, A3: `umi`, EN: `United States Minor Outlying Islands`, RU: `Внешние малые острова США`},
	{A2: `uy`, A3: `ury`, EN: `Uruguay`, RU: `Уругвай`},
	{A2: `uz`, A3: `uzb`, EN: `Uzbekistan`, RU: `Узбекистан`},
	{A2: `vu`, A3: `vut`, EN: `Vanuatu`, RU: `Вануату`},
	{A2: `ve`, A3: `ven`, EN: `Venezuela`, RU: `Венесуэла`},
	{A2: `vn`, A3: `vnm`, EN: `Vietnam`, RU: `Вьетнам`},
	{A2: `vg`, A3: `vgb`, EN: `Virgin Islands (British)`, RU: `Виргинские Острова (Великобритания)`},
	{A2: `vi`, A3: `vir`, EN: `Virgin Islands (U.S.)`, RU: `Виргинские Острова (США)`},
	{A2: `wf`, A3: `wlf`, EN: `Wallis and Futuna`, RU: `Уоллис и Футуна`},
	{A2: `eh`, A3: `esh`, EN: `Western Sahara`, RU: `САДР`},
	{A2: `ye`, A3: `yem`, EN: `Yemen`, RU: `Йемен`},
	{A2: `zm`, A3: `zmb`, EN: `Zambia`, RU: `Замбия`},
	{A2: `zw`, A3: `zwe`, EN: `Zimbabwe`, RU: `Зимбабве`},
}
